"""Add fields to Task model

Revision ID: 27d802a57dbd
Revises: 9c8d96ce8dfc
Create Date: 2025-04-26 02:58:01.164540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d802a57dbd'
down_revision = '9c8d96ce8dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_effort', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('logged_time', sa.Float(), nullable=True))
        batch_op.drop_column('priority')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.INTEGER(), nullable=True))
        batch_op.drop_column('logged_time')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('start_date')
        batch_op.drop_column('estimated_effort')

    # ### end Alembic commands ###
