"""Add TaskSegment model

Revision ID: 308154479b85
Revises: 928cf3fa8aff
Create Date: 2025-05-10 18:02:46.210289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308154479b85'
down_revision = '928cf3fa8aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('segment_start_datetime', sa.DateTime(), nullable=False),
    sa.Column('segment_end_datetime', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_segment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_segment_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('due_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_time', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.TIME(), nullable=True))

    with op.batch_alter_table('task_segment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_segment_task_id'))

    op.drop_table('task_segment')
    # ### end Alembic commands ###
