"""Add completion_date to task

Revision ID: 355ec4707362
Revises: 9f7b3a3e5db4
Create Date: 2025-05-03 02:16:57.165891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355ec4707362'
down_revision = '9f7b3a3e5db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('completion_date')

    # ### end Alembic commands ###
