"""Add completion_date to task

Revision ID: 459090156a81
Revises: 355ec4707362
Create Date: 2025-05-03 03:54:17.703614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459090156a81'
down_revision = '355ec4707362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_milestone')
        batch_op.drop_column('completion_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_milestone', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
