"""Add TaskNote model

Revision ID: 883090262996
Revises: 6db931fe0d47
Create Date: 2025-05-11 23:26:58.238494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883090262996'
down_revision = '6db931fe0d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_note_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_note_task_id'))

    op.drop_table('task_note')
    # ### end Alembic commands ###
