"""Add criticality to Sprint using server_default

Revision ID: 8b296c07c944
Revises: b9c657a1fdce
Create Date: 2025-04-28 02:19:05.942066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b296c07c944'
down_revision = 'b9c657a1fdce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criticality', sa.String(length=50), server_default='Normal', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprint', schema=None) as batch_op:
        batch_op.drop_column('criticality')

    # ### end Alembic commands ###
