"""add start_time and due_time to Task

Revision ID: 928cf3fa8aff
Revises: cc26d6b649f3
Create Date: 2025-05-10 10:20:13.086289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928cf3fa8aff'
down_revision = 'cc26d6b649f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_milestone', schema=None) as batch_op:
        batch_op.alter_column('planned_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('actual_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('project_risk', schema=None) as batch_op:
        batch_op.alter_column('identified_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('trend',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('due_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('due_time')
        batch_op.drop_column('start_time')

    with op.batch_alter_table('project_risk', schema=None) as batch_op:
        batch_op.alter_column('trend',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('identified_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('project_milestone', schema=None) as batch_op:
        batch_op.alter_column('actual_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('planned_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
