"""temporary removal of specialist_name

Revision ID: 95eeca32d797
Revises: 8b296c07c944
Create Date: 2025-04-29 00:21:54.884588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95eeca32d797'
down_revision = '8b296c07c944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialist_name', sa.String(length=150), nullable=True))
        batch_op.create_index(batch_op.f('ix_task_specialist_name'), ['specialist_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_specialist_name'))
        batch_op.drop_column('specialist_name')

    # ### end Alembic commands ###
