"""Add ProjectMilestone Model

Revision ID: cc26d6b649f3
Revises: d49b3d434def
Create Date: 2025-05-07 23:54:17.933355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc26d6b649f3'
down_revision = 'd49b3d434def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Cria a tabela project_milestone
    op.create_table('project_milestone',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('planned_date', sa.Date(), nullable=False),
        sa.Column('actual_date', sa.Date(), nullable=True),
        sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'DELAYED', name='milestonestatus'), nullable=False, server_default='PENDING'),
        sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='milestonecriticality'), nullable=False, server_default='MEDIUM'),
        sa.Column('is_checkpoint', sa.Boolean(), nullable=True, server_default=sa.false()),
        sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column('backlog_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['backlog_id'], ['backlog.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Mantém as alterações originais de project_risk (se necessário, embora idealmente estivessem em outra migração)
    with op.batch_alter_table('project_risk', schema=None) as batch_op:
        batch_op.alter_column('identified_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('trend',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Reverte as alterações de project_risk
    with op.batch_alter_table('project_risk', schema=None) as batch_op:
        batch_op.alter_column('trend',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('identified_date',
               existing_type=sa.DATETIME(),
               nullable=True)
               
    # Remove a tabela project_milestone
    op.drop_table('project_milestone')

    # ### end Alembic commands ###
