"""Add project milestones and risks models

Revision ID: d49b3d434def
Revises: 459090156a81
Create Date: 2025-05-07 22:04:36.752879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49b3d434def'
down_revision = '459090156a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_date', sa.DateTime(), nullable=False),
    sa.Column('actual_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'DELAYED', name='milestonestatus'), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='milestonecriticality'), nullable=False),
    sa.Column('is_checkpoint', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('backlog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['backlog_id'], ['backlog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='riskimpact'), nullable=False),
    sa.Column('probability', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='riskprobability'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MITIGATED', 'RESOLVED', name='riskstatus'), nullable=False),
    sa.Column('identified_date', sa.DateTime(), nullable=True),
    sa.Column('resolved_date', sa.DateTime(), nullable=True),
    sa.Column('mitigation_plan', sa.Text(), nullable=True),
    sa.Column('contingency_plan', sa.Text(), nullable=True),
    sa.Column('responsible', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('trend', sa.String(length=50), nullable=False),
    sa.Column('backlog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['backlog_id'], ['backlog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_risk')
    op.drop_table('project_milestone')
    # ### end Alembic commands ###
